### PR TITLE
F/search results scroll

### PR DESCRIPTION
**Pull request by kevinjihwanlee**

### CODE REVIEW

**Comment by kevinjihwanlee** [comment]
[Search results scroll](https://trello.com/c/WIAZr9NT/28-search-results-scroll)

**Comment by kevinjihwanlee** [comment]
[Search results scroll](https://trello.com/c/WIAZr9NT/28-search-results-scroll)

**Comment by Joonpark13** [comment]
screen shot 2018-10-21 at 9 59 57 am

Looks like there's a little bit of extra space when I scroll to the bottom. Can you look into that?

**Review by Joonpark13 — CHANGES_REQUESTED** [review]
screen shot 2018-10-21 at 9 59 57 am

Looks like there's a little bit of extra space when you scroll to the bottom. Can you look into that?

**Review by Joonpark13 — APPROVED** [review]

**Pull request merged**
